version: '3'

services:
  app:
    container_name: pets-of-road-application
    build: .
    ports:
      - '3030:3030'
    depends_on:
      - db
    volumes:
      - .:/usr/app

  db:
    image: mysql
    container_name: pets-of-road-database
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: PETS-OF-ROAD-DB
      MYSQL_ROOT_PASSWORD: senhaprovisoria

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080